name: Build and Deploy to Production

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Manual Deployment Reason'
        required: false
        default: 'Rebuild gatsby'
  push:
    branches:
      - master

jobs:
  ping-dev-server:
    name: Ping Prod server
    runs-on: ubuntu-latest
    steps:
      - name: Ping dev api
        run: curl ${{ secrets.PROD_STRAPI_API_URL }}
  lint-and-test:
    name: Syntax check (Eslint) and Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Run Eslint
        run: yarn lint
      # - name: Run Tests
      #   run: yarn test
  build-and-deploy:
    name: Build and deploy the site to staging
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Build website
        env:
          REACT_APP_STRAPI_API: ${{ secrets.PROD_STRAPI_API_URL }}
          REACT_APP_FRONT_END_URL: ${{ secrets.PROD_REACT_APP_FRONT_END_URL }}
        run: CI=false yarn build
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.PROD_AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'build'
  invalidate:
    name: Invalidate cloudfront cache
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id "${{ secrets.PROD_CLOUD_FRONT_DISTRIBUTION }}" --paths "/*"
